name: gwallet # TODO: 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: multi-currency crossplatform thin opensource crypto brainwallet # 79 char long summary
description: |
  Minimalistic and pragmatist crossplatform multicurrency lightweight opensource
  brainwallet for people that want to hold the most important cryptocurrencies
  in the same application with ease and peace of mind.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gwallet:
    command: sh $SNAP/usr/bin/gwallet

parts:
  build-and-install-console-frontend:
    # See 'snapcraft plugins'
    plugin: make
    source: ..
    override-build: |
      # pulls mono by default
      apt install -y fsharp

      # needed by our nuget infrastructure
      apt install -y curl

      ./configure.sh --prefix=$SNAPCRAFT_PART_INSTALL/usr
      make
      make install

