image: ubuntu:18.04

before_script:
  - apt-get update
  # needed to download NuGet
  - apt-get install -y curl

stages:
  - build
  - test
  - packaging

stockmono_build:
  stage: build
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp
    - mono --version

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

    # make sure it has been installed correctly
    - which gwallet

stockmono_test:
  stage: test
  script:
    # https://askubuntu.com/a/1013396
    - DEBIAN_FRONTEND=noninteractive apt-get install -y nuget mono-complete mono-xbuild fsharp

    - time (apt-get install -y nunit-console &&
            ./configure.sh &&
            make &&
            make check)

newmono_build:
  stage: build
  artifacts:
    paths:
      - bin/*.zip
    expire_in: 1 week
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - time (./configure.sh && make && make install)
    # so that we log the version of nuget for when it works
    - make nuget

    # make sure it has been installed correctly
    - which gwallet

    - apt-get install -y zip
    - make zip

newmono_test:
  stage: test
  script:
    - ./scripts/install_mono_from_microsoft_deb_packages.sh

    - apt install -y nunit-console

    - time (./configure.sh && make && make check)

snap_build:
  stage: packaging
  script:
    - apt install -y snapcraft
    - DEBIAN_FRONTEND=noninteractive ./scripts/build_snap.sh
