name: geewallet # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: minimalistic and pragmatist crossplatform lightweight opensource brainwallet # 79 char long summary
description: |
  geewallet is a minimalistic and pragmatist crossplatform lightweight opensource
  brainwallet for people that want to hold the most important cryptocurrencies
  in the same application with ease and peace of mind.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  geewallet:
    command: sh $SNAP/usr/bin/gwallet-gtk

parts:
  geewallet:
    plugin: make
    source: .
    override-build: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
      apt update

      # mono related packages
      apt install -y mono-devel
      apt install -y fsharp
      apt install -y libgtk2.0-cil-dev

      # dotnet related packages
      apt install -y wget
      wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      dpkg -i packages-microsoft-prod.deb
      apt install -y apt-transport-https
      apt update
      apt install -y dotnet-sdk-2.1

      # geewallet source
      ./configure.sh --prefix=$SNAPCRAFT_PART_INSTALL/usr
      make
      make install
